docker rmi codewisdom/ts-train-service:latest
docker rmi codewisdom/ts-ui-dashboard:latest
docker rmi codewisdom/ts-auth-service:latest
docker rmi codewisdom/ts-user-service:latest
docker rmi codewisdom/ts-verification-code-service:latest
docker rmi codewisdom/ts-contacts-service:latest
docker rmi codewisdom/ts-order-service:latest
docker rmi codewisdom/ts-order-other-service:latest
docker rmi codewisdom/ts-config-service:latest
docker rmi codewisdom/ts-station-service:latest
docker rmi codewisdom/ts-travel-service:latest
docker rmi codewisdom/ts-travel2-service:latest
docker rmi codewisdom/ts-preserve-service:latest
docker rmi codewisdom/ts-preserve-other-service:latest
docker rmi codewisdom/ts-basic-service:latest
docker rmi codewisdom/ts-ticketinfo-service:latest
docker rmi codewisdom/ts-price-service:latest
docker rmi codewisdom/ts-notification-service:latest
docker rmi codewisdom/ts-security-service:latest
docker rmi codewisdom/ts-inside-payment-service:latest
docker rmi codewisdom/ts-execute-service:latest
docker rmi codewisdom/ts-payment-service:latest
docker rmi codewisdom/ts-rebook-service:latest
docker rmi codewisdom/ts-cancel-service:latest
docker rmi codewisdom/ts-route-service:latest
docker rmi codewisdom/ts-assurance-service:latest
docker rmi codewisdom/ts-seat-service:latest
docker rmi codewisdom/ts-travel-plan-service:latest
docker rmi codewisdom/ts-route-plan-service:latest
docker rmi codewisdom/ts-food-map-service:latest
docker rmi codewisdom/ts-food-service:latest
docker rmi codewisdom/ts-consign-price-service:latest
docker rmi codewisdom/ts-consign-service:latest
docker rmi codewisdom/ts-admin-order-service:latest
docker rmi codewisdom/ts-admin-basic-info-service:latest
docker rmi codewisdom/ts-admin-route-service:latest
docker rmi codewisdom/ts-admin-travel-service:latest
docker rmi codewisdom/ts-admin-user-service:latest
docker rmi codewisdom/ts-news-service:latest
docker rmi codewisdom/ts-ticket-office-service:latest
docker rmi codewisdom/ts-voucher-service:latest

docker rmi ts/ts-train-service:latest
docker rmi ts/ts-ui-dashboard:latest
docker rmi ts/ts-auth-service:latest
docker rmi ts/ts-user-service:latest
docker rmi ts/ts-verification-code-service:latest
docker rmi ts/ts-contacts-service:latest
docker rmi ts/ts-order-service:latest
docker rmi ts/ts-order-other-service:latest
docker rmi ts/ts-config-service:latest
docker rmi ts/ts-station-service:latest
docker rmi ts/ts-travel-service:latest
docker rmi ts/ts-travel2-service:latest
docker rmi ts/ts-preserve-service:latest
docker rmi ts/ts-preserve-other-service:latest
docker rmi ts/ts-basic-service:latest
docker rmi ts/ts-ticketinfo-service:latest
docker rmi ts/ts-price-service:latest
docker rmi ts/ts-notification-service:latest
docker rmi ts/ts-security-service:latest
docker rmi ts/ts-inside-payment-service:latest
docker rmi ts/ts-execute-service:latest
docker rmi ts/ts-payment-service:latest
docker rmi ts/ts-rebook-service:latest
docker rmi ts/ts-cancel-service:latest
docker rmi ts/ts-route-service:latest
docker rmi ts/ts-assurance-service:latest
docker rmi ts/ts-seat-service:latest
docker rmi ts/ts-travel-plan-service:latest
docker rmi ts/ts-route-plan-service:latest
docker rmi ts/ts-food-map-service:latest
docker rmi ts/ts-food-service:latest
docker rmi ts/ts-consign-price-service:latest
docker rmi ts/ts-consign-service:latest
docker rmi ts/ts-admin-order-service:latest
docker rmi ts/ts-admin-basic-info-service:latest
docker rmi ts/ts-admin-route-service:latest
docker rmi ts/ts-admin-travel-service:latest
docker rmi ts/ts-admin-user-service:latest
docker rmi ts/ts-news-service:latest
docker rmi ts/ts-ticket-office-service:latest
docker rmi ts/ts-voucher-service:latest
